export const data = [
  {
    ID: 1,
    Nombre: "Ibuprofeno",
    Laboratorio: "Laboratorios XYZ",
    Dosis: "400 mg",
    Registro_Sanitario: "12345-ABC",
    Via_Administracion: "Oral",
  },
  {
    ID: 2,
    Nombre: "Paracetamol",
    Laboratorio: "Laboratorios ABC",
    Dosis: "500 mg",
    Registro_Sanitario: "67890-DEF",
    Via_Administracion: "Oral",
  },
  {
    ID: 3,
    Nombre: "Amoxicilina",
    Laboratorio: "Laboratorios QRS",
    Dosis: "250 mg",
    Registro_Sanitario: "13579-GHI",
    Via_Administracion: "Oral",
  },
  {
    ID: 4,
    Nombre: "Omeprazol",
    Laboratorio: "Laboratorios WXY",
    Dosis: "20 mg",
    Registro_Sanitario: "24680-JKL",
    Via_Administracion: "Oral",
  },
  {
    ID: 5,
    Nombre: "Loratadina",
    Laboratorio: "Laboratorios MNO",
    Dosis: "10 mg",
    Registro_Sanitario: "54321-PQR",
    Via_Administracion: "Oral",
  },
  {
    ID: 6,
    Nombre: "Diazepam",
    Laboratorio: "Laboratorios STU",
    Dosis: "5 mg",
    Registro_Sanitario: "98765-TUV",
    Via_Administracion: "Oral",
  },
  {
    ID: 7,
    Nombre: "Furosemida",
    Laboratorio: "Laboratorios VWX",
    Dosis: "40 mg",
    Registro_Sanitario: "87654-WXY",
    Via_Administracion: "Oral",
  },
  {
    ID: 8,
    Nombre: "Atorvastatina",
    Laboratorio: "Laboratorios YZA",
    Dosis: "20 mg",
    Registro_Sanitario: "45678-ZAB",
    Via_Administracion: "Oral",
  },
  {
    ID: 9,
    Nombre: "Metformina",
    Laboratorio: "Laboratorios BCD",
    Dosis: "850 mg",
    Registro_Sanitario: "34567-BCD",
    Via_Administracion: "Oral",
  },
  {
    ID: 10,
    Nombre: "Ciprofloxacino",
    Laboratorio: "Laboratorios CDE",
    Dosis: "500 mg",
    Registro_Sanitario: "23456-CDE",
    Via_Administracion: "Oral",
  },
  {
    ID: 11,
    Nombre: "Oxycodona",
    Laboratorio: "Laboratorios DEF",
    Dosis: "10 mg",
    Registro_Sanitario: "12345-DEF",
    Via_Administracion: "Oral",
  },
  {
    ID: 12,
    Nombre: "Cetirizina",
    Laboratorio: "Laboratorios EFG",
    Dosis: "10 mg",
    Registro_Sanitario: "98765-EFG",
    Via_Administracion: "Oral",
  },
  {
    ID: 13,
    Nombre: "Esomeprazol",
    Laboratorio: "Laboratorios FGH",
    Dosis: "20 mg",
    Registro_Sanitario: "87654-FGH",
    Via_Administracion: "Oral",
  },
  {
    ID: 14,
    Nombre: "Levofloxacino",
    Laboratorio: "Laboratorios GHI",
    Dosis: "500 mg",
    Registro_Sanitario: "76543-GHI",
    Via_Administracion: "Oral",
  },
];
