export const data = [
  {
    id: 1,
    Usuario: "Juan Gomez",
    Estado: "Activo",
    Ubicación: "Pereira",
    Teléfono: "3204592911",
    Tipo_Usuario: "Normal",
  },
  {
    id: 2,
    Usuario: "María Rodríguez",
    Estado: "Activo",
    Ubicación: "Bogotá",
    Teléfono: "3157891234",
    Tipo_Usuario: "Administrador",
  },
  {
    id: 3,
    Usuario: "Carlos Pérez",
    Estado: "Inactivo",
    Ubicación: "Medellín",
    Teléfono: "3104567890",
    Tipo_Usuario: "Normal",
  },
  {
    id: 4,
    Usuario: "Ana García",
    Estado: "Activo",
    Ubicación: "Cali",
    Teléfono: "3176543210",
    Tipo_Usuario: "Normal",
  },
  {
    id: 5,
    Usuario: "Luisa Martínez",
    Estado: "Activo",
    Ubicación: "Barranquilla",
    Teléfono: "3009876543",
    Tipo_Usuario: "Normal",
  },
  {
    id: 6,
    Usuario: "Pedro Sánchez",
    Estado: "Inactivo",
    Ubicación: "Cartagena",
    Teléfono: "3012345678",
    Tipo_Usuario: "Administrador",
  },
  {
    id: 7,
    Usuario: "Laura Torres",
    Estado: "Activo",
    Ubicación: "Cúcuta",
    Teléfono: "3134567890",
    Tipo_Usuario: "Normal",
  },
  {
    id: 8,
    Usuario: "Diego Ramírez",
    Estado: "Activo",
    Ubicación: "Santa Marta",
    Teléfono: "3219876543",
    Tipo_Usuario: "Normal",
  },
  {
    id: 9,
    Usuario: "Camila Vargas",
    Estado: "Activo",
    Ubicación: "Pasto",
    Teléfono: "3176543210",
    Tipo_Usuario: "Normal",
  },
  {
    id: 10,
    Usuario: "Jorge López",
    Estado: "Activo",
    Ubicación: "Manizales",
    Teléfono: "3134567890",
    Tipo_Usuario: "Normal",
  },
  {
    id: 11,
    Usuario: "Valentina Herrera",
    Estado: "Inactivo",
    Ubicación: "Villavicencio",
    Teléfono: "3109876543",
    Tipo_Usuario: "Normal",
  },
  {
    id: 12,
    Usuario: "Santiago Castro",
    Estado: "Activo",
    Ubicación: "Ibagué",
    Teléfono: "3006543210",
    Tipo_Usuario: "Normal",
  },
  {
    id: 13,
    Usuario: "Natalia Rojas",
    Estado: "Activo",
    Ubicación: "Armenia",
    Teléfono: "3112345678",
    Tipo_Usuario: "Normal",
  },
  {
    id: 14,
    Usuario: "Andrés Gómez",
    Estado: "Activo",
    Ubicación: "Bucaramanga",
    Teléfono: "3189876543",
    Tipo_Usuario: "Normal",
  },
];
